language: python
python:
  - "3.6"
git:
  depth: false
install:
# install from requirements first, because that installs the non-binary psycopg2
  - pip install -c constraints.txt -r requirements.txt
  - pip install -c constraints.txt -e .
script:
  - flake8
  - black --check print-logs run-query setup.py ethindex
  - mypy --ignore-missing-imports ethindex
#  - coverage run --source=ethindex -m py.test tests
#after_success:
#  - coverage report
branches:
  only:
  - master
  - develop
